#!/usr/bin/env node
/**
 * Scans public/assets for generated WebP images and writes
 * src/data/images.generated.ts: size + a tiny blurred placeholder (LQIP) per image.
 * Slots without an image keep the phase-tinted gradient placeholder.
 *
 *   node scripts/build-lqip.mjs
 */
import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const assets = path.join(root, "public", "assets");
const out = path.join(root, "src", "data", "images.generated.ts");

const walk = (dir) =>
  fs.existsSync(dir)
    ? fs.readdirSync(dir, { withFileTypes: true }).flatMap((d) => (d.isDirectory() ? walk(path.join(dir, d.name)) : [path.join(dir, d.name)]))
    : [];

const files = walk(assets)
  .filter((f) => f.endsWith(".webp") && !f.endsWith("-sm.webp"))
  .sort();

const entries = [];
for (const file of files) {
  const rel = path.relative(path.join(root, "public"), file).split(path.sep).join("/");
  const img = sharp(file);
  const { width, height } = await img.metadata();
  const tiny = await img.clone().resize(24, Math.max(1, Math.round((24 * height) / width))).blur(1.2).webp({ quality: 42 }).toBuffer();
  const smFile = file.replace(/\.webp$/, "-sm.webp");
  const sm = fs.existsSync(smFile);
  // Content hash → ?v= on the URL, so regenerated art is never served from a stale cache.
  const hash = createHash("sha1").update(fs.readFileSync(file));
  if (sm) hash.update(fs.readFileSync(smFile));
  const v = hash.digest("hex").slice(0, 10);
  entries.push(`  ${JSON.stringify(rel)}: { w: ${width}, h: ${height}, sm: ${sm}, v: "${v}", lqip: "data:image/webp;base64,${tiny.toString("base64")}" },`);
}

const ts = `// Generated by scripts/build-lqip.mjs — do not edit by hand.
// Maps an image path to its size and a tiny blurred placeholder. Paths that
// are missing here render the phase-tinted gradient placeholder instead.
export interface ImageMeta {
  w: number;
  h: number;
  lqip: string;
  sm: boolean;
  /** Content hash, appended as ?v= for cache busting. */
  v: string;
}

export const IMAGE_META: Record<string, ImageMeta> = {${entries.length ? `\n${entries.join("\n")}\n` : ""}};
`;
fs.writeFileSync(out, ts, "utf8");
console.log(`✔ ${entries.length} image placeholders → ${path.relative(root, out)}`);
